version: '3.1'

services:

  postgres_db:
    container_name: movie_postgres_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
