"""add year

Revision ID: 4683563045ee
Revises: 7bbabe0dba76
Create Date: 2022-12-12 18:42:01.913786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4683563045ee'
down_revision = '7bbabe0dba76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_index('ix_song_artist', table_name='song')
    op.drop_index('ix_song_id', table_name='song')
    op.drop_index('ix_song_name', table_name='song')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_song_name', 'song', ['name'], unique=False)
    op.create_index('ix_song_id', 'song', ['id'], unique=False)
    op.create_index('ix_song_artist', 'song', ['artist'], unique=False)
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
